### ISSUE TITLE
i am getting error while running the yarn run watch

### ISSUE THREAD

**Issue by Thrilok28021996** [AllAboutCode/EduBlocks#158]
i am getting error while running the yarn run watch. can anyone help me with this .This is the error i am getting 

events.js:467
  var copy = new Array(n);
             ^

RangeError: Maximum call stack size exceeded
    at arrayClone (events.js:467:14)
    at Stream.emit (events.js:192:23)
    at Stream.<anonymous> (D:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:194:15)
    at Stream.<anonymous> (D:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:194:15)
    at Stream.<anonymous> (D:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:194:15)
    at Stream.<anonymous> (D:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:194:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fernandesvinicius** [comment]
I had the same error when i tryed to run in windows. Thats because in package.json file is missing something to put a break or something like that (i don't know exactly how to explain). So, i fixed that like this:
go to EduBlocks/ui and open package.json. In vscode i change the line number 10:

 "watchify": "Powershell Start-Sleep -s 1 && watchify -t brfs -t folderify -t  C:\\Users\\myUserHere\\Documents\\GitHub\\EduBlocks\\ui\\build\\main.js -o dist/main.js",
 
 I just put **-t** in front of watchify and brfs and folderify
